/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs655.Refactoring_Examples.app.src.main.java.Refactoring_Examples;

public class App {
    public String getGreeting() {
        return "Review Before and After Code for each Refactoring";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
